[package]
name = "gentle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
dashmap = "5.4.0"
include_dir = "0.7.3"
rhai = { version = "1.11.0", features = ["sync"] }
structopt = "0.3.26"
thiserror = "1.0.37"

[[bin]]
name = "gtl"
path = "src/main.rs"
